#!/usr/bin/env zsh
# JEBAT CLI completion — Zsh
#
# Source this file in your .zshrc:
#   source /path/to/jebat-core/shell/jebat-completion.zsh
#
# Requires compinit to be loaded. Add to your .zshrc before sourcing:
#   autoload -Uz compinit && compinit
#
# Auto-generated by JEBAT Phase 4 — 2026-05-31

#compdef jebat

_jebat() {
    local -a subcommands
    subcommands=(
        'status:Show system status'
        'loop:Ultra-Loop control'
        'think:Run thinking session'
        'memory:Memory operations'
        'config:Configuration management'
        'llm-providers:List supported LLM providers'
        'llm-config:Show resolved LLM configuration'
        'llm-auth:Show provider auth status'
        'llm-best-provider:Show best configured provider'
        'doctor:Check LLM/provider health'
        'mode-guide:Print JEBAT assistant guide path'
        'skills:Inspect TokGuru skills'
        'chat:Chat with LLM (one-shot)'
        'chat-project:Chat with project context'
        'chat-repl:Interactive REPL with tool-calling'
        'tools:List and inspect registered tools'
        'file:File operations'
        'exec:Run shell commands'
        'wiki:Knowledge base management'
        'delegate:Spawn subagents for delegated tasks'
        'cron:Schedule recurring tasks'
        'safety:Security: audit log, sandbox, classification'
        'session:Session management and search'
        'mcp:MCP server management'
        'search:Web search'
        'agent:One-shot agent task'
        'free-models:List free/cheap AI models'
        'cost:Token cost dashboard'
        'undo:Undo file changes'
        'telemetry:Usage analytics'
        'sandbox:Docker sandbox for code execution'
        'plugins:Manage JEBAT plugins'
    )

    _arguments -C \
        '1: :{_describe "jebat subcommand" subcommands}' \
        '*::arg:->args'

    case $words[1] in
        file)
            local -a file_subs
            file_subs=('read:Read a file' 'write:Write a file' 'patch:Apply patch' 'search:Search files' 'undo:Undo file changes')
            _describe "file subcommand" file_subs
            ;;
        wiki)
            local -a wiki_subs
            wiki_subs=('create:Create a wiki page' 'read:Read a wiki page' 'edit:Edit a wiki page' 'delete:Delete a wiki page' 'list:List wiki pages' 'search:Search wiki pages' 'link:Show backlinks' 'stats:Show wiki statistics')
            _describe "wiki subcommand" wiki_subs
            ;;
        cron)
            local -a cron_subs
            cron_subs=('add:Add a cron job' 'list:List cron jobs' 'run:Run a cron job now' 'pause:Pause a cron job' 'resume:Resume a cron job' 'remove:Remove a cron job')
            _describe "cron subcommand" cron_subs
            ;;
        delegate)
            local -a delegate_subs
            delegate_subs=('run:Run a delegated task' 'list:List active delegations' 'status:Show delegation status')
            _describe "delegate subcommand" delegate_subs
            ;;
        safety)
            local -a safety_subs
            safety_subs=('audit:View audit log' 'clear-audit:Clear audit log' 'sandbox-on:Enable sandbox mode' 'sandbox-off:Disable sandbox mode' 'classify:Classify command safety tier')
            _describe "safety subcommand" safety_subs
            ;;
        session)
            local -a session_subs
            session_subs=('list:List recent sessions' 'search:Search past conversations')
            _describe "session subcommand" session_subs
            ;;
        mcp)
            local -a mcp_subs
            mcp_subs=('serve:Serve MCP' 'ide-config:Generate IDE config' 'start-all:Start all MCP servers')
            _describe "mcp subcommand" mcp_subs
            ;;
        config)
            local -a config_subs
            config_subs=('show:Show configuration' 'set:Set config value' 'get:Get config value')
            _describe "config subcommand" config_subs
            ;;
        loop)
            local -a loop_subs
            loop_subs=('start:Start ultra loop')
            _describe "loop subcommand" loop_subs
            ;;
    esac
}

_jebat "$@"