#!/usr/bin/env bash
# JEBAT CLI completion — Bash
#
# Source this file in your .bashrc or .bash_profile:
#   source /path/to/jebat-core/shell/jebat-completion.bash
#
# Auto-generated by JEBAT Phase 4 — 2026-05-31

_jebat_completion() {
    local cur prev words cword
    _init_completion || return

    # Top-level subcommands
    local commands="status loop think memory config llm-providers llm-config
        llm-auth llm-best-provider doctor mode-guide skills chat chat-project
        chat-repl tools file exec wiki delegate cron safety session mcp search
        agent free-models cost undo telemetry sandbox plugins"

    if [[ $cword -eq 1 ]]; then
        COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
        return
    fi

    local cmd="${words[1]}"
    case "$cmd" in
        file)
            local file_subs="read write patch search undo"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${file_subs}" -- "${cur}"))
            else
                _filedir
            fi
            ;;
        exec)
            # No subcommands — just a command string
            COMPREPLY=()
            ;;
        wiki)
            local wiki_subs="create read edit delete list search link stats"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${wiki_subs}" -- "${cur}"))
            fi
            ;;
        cron)
            local cron_subs="add list run pause resume remove"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${cron_subs}" -- "${cur}"))
            fi
            ;;
        delegate)
            local delegate_subs="run list status"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${delegate_subs}" -- "${cur}"))
            fi
            ;;
        safety)
            local safety_subs="audit clear-audit sandbox-on sandbox-off classify"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${safety_subs}" -- "${cur}"))
            fi
            ;;
        session)
            local session_subs="list search"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${session_subs}" -- "${cur}"))
            fi
            ;;
        llm-providers|llm-config|llm-auth|llm-best-provider|doctor|mode-guide|skills|memory)
            # These have no subcommands
            COMPREPLY=()
            ;;
        mcp)
            local mcp_subs="serve ide-config start-all"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${mcp_subs}" -- "${cur}"))
            fi
            ;;
        search)
            # query string — no file completion
            COMPREPLY=()
            ;;
        agent)
            # task string — no file completion
            COMPREPLY=()
            ;;
        chat|chat-repl|chat-project)
            # message or project paths
            COMPREPLY=()
            ;;
        config)
            local config_subs="show set get"
            if [[ $cword -eq 2 ]]; then
                COMPREPLY=($(compgen -W "${config_subs}" -- "${cur}"))
            fi
            ;;
        free-models)
            # no subcommands
            COMPREPLY=()
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _jebat_completion jebat