"""`jebat init` — repo-scan AGENTS.md generator (claude-code /init style).

Scans the current workspace (stack, entrypoints, test layout, existing agent
docs) and writes an AGENTS.md capture file. Existing AGENTS.md is backed up,
never silently overwritten.
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Dict, List, Optional, Sequence

from jebat_cli_new.theme import C, cprint


STACK_MARKERS: List[tuple] = [
    # (files that prove it, stack label)
    (("pyproject.toml",), "Python (pyproject)"),
    (("requirements.txt", "requirements.prod.txt"), "Python (pip)"),
    (("package.json",), "Node/TypeScript"),
    (("pnpm-lock.yaml",), "pnpm workspace"),
    (("Cargo.toml",), "Rust"),
    (("go.mod",), "Go"),
    (("docker-compose.yml", "docker-compose.prod.yml"), "Docker Compose"),
    (("Dockerfile",), "Docker"),
    (("prisma/schema.prisma", "apps/api/prisma/schema.prisma"), "Prisma ORM"),
    (("tailwind.config.js", "tailwind.config.ts"), "Tailwind CSS"),
    (("next.config.js", "next.config.mjs", "next.config.ts"), "Next.js"),
    (("Makefile",), "Make"),
]

DOC_HINTS = ("README.md", "CLAUDE.md", "AGENTS.md", "PROJECT_START.md", "DESIGN.md")


def _scan(root: Path) -> Dict[str, object]:
    files = {p.name for p in root.iterdir() if p.is_file()} if root.is_dir() else set()
    dirs = {p.name for p in root.iterdir() if p.is_dir()} if root.is_dir() else set()
    stacks = [label for markers, label in STACK_MARKERS if any(m in files for m in markers)]
    # shallow source layout hints (1 level)
    layout = sorted(
        d for d in ("src", "apps", "packages", "server", "web", "tests", "scripts", "infra", "docs")
        if d in dirs
    )
    test_files = 0
    for pattern in ("test_*.py", "*_test.ts", "*.test.ts", "*.spec.ts", "*.test.js"):
        test_files += len(list(root.rglob(pattern))) if root.is_dir() else 0
        if test_files > 5000:
            break
    docs = [d for d in DOC_HINTS if d in files]
    entrypoints = []
    for cand in ("main.py", "app.py", "index.ts", "src/index.ts", "server/index.ts"):
        if (root / cand).exists():
            entrypoints.append(cand)
    return {
        "stacks": stacks,
        "layout": layout,
        "docs": docs,
        "entrypoints": entrypoints,
        "test_files": test_files,
        "top_files": sorted(files)[:40],
    }


def _render_agents_md(root: Path, scan: Dict[str, object]) -> str:
    name = root.name or "workspace"
    stacks: List[str] = scan["stacks"]  # type: ignore[assignment]
    layout: List[str] = scan["layout"]  # type: ignore[assignment]
    docs: List[str] = scan["docs"]  # type: ignore[assignment]
    entrypoints: List[str] = scan["entrypoints"]  # type: ignore[assignment]
    lines = [
        f"# {name} — Agent Notes",
        "",
        f"<!-- Generated by `jebat init` on {time.strftime('%Y-%m-%d %H:%M')} — edit freely, regenerate deliberately -->",
        "",
        "## Stack",
    ]
    lines += [f"- {s}" for s in stacks] or ["- (undetected — fill in)"]
    if layout:
        lines += ["", "## Layout"] + [f"- `{d}/`" for d in layout]
    if entrypoints:
        lines += ["", "## Entrypoints"] + [f"- `{e}`" for e in entrypoints]
    lines += [
        "",
        "## Tests",
        f"- ~{scan['test_files']} test files discovered (patterns: test_*.py, *.test.ts, *.spec.ts)",
        "- Run the suite before delivering changes.",
        "",
        "## Conventions",
        "- Load nearest local AGENTS.md / DESIGN.md before editing a subtree.",
        "- Verify claims by running code, not by asserting.",
    ]
    if docs:
        lines += ["", "## Related docs"] + [f"- `{d}`" for d in docs]
    lines += ["", "## Add here", "- Build commands, gotchas, deploy targets, invariants worth enforcing."]
    return "\n".join(lines) + "\n"


def run_init(root: Optional[Path] = None, force: bool = False) -> int:
    root = (root or Path.cwd()).resolve()
    if not root.is_dir():
        cprint(f"✗ not a directory: {root}", C.RED)
        return 1
    scan = _scan(root)
    target = root / "AGENTS.md"
    if target.exists() and not force:
        stamp = time.strftime("%Y%m%d-%H%M%S")
        backup = target.with_name(f"AGENTS.md.bak-{stamp}-init")
        backup.write_text(target.read_text(encoding="utf-8"), encoding="utf-8")
        cprint(f"  backed up existing AGENTS.md → {backup.name}", C.YELLOW)
    content = _render_agents_md(root, scan)
    target.write_text(content, encoding="utf-8")
    cprint(f"✓ wrote {target}", C.GREEN)
    cprint(f"  stack: {', '.join(scan['stacks']) or 'unknown'} · layout: {', '.join(scan['layout']) or '—'} · tests: ~{scan['test_files']}", C.GRAY)
    return 0


def run_init_command(tokens: Sequence[str]) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        prog="jebat init",
        description="Scan the workspace and generate an AGENTS.md capture file.",
    )
    parser.add_argument("--dir", default=".", help="workspace root (default: cwd)")
    parser.add_argument("--force", action="store_true", help="regenerate even if AGENTS.md exists (backs up first)")
    ns = parser.parse_args(list(tokens))
    return run_init(Path(ns.dir).expanduser().resolve(), force=ns.force)
