"""JEBAT SDK — Public exports."""

from .client import JebatClient, AsyncJebatClient, create_client, create_async_client
from .config import ClientConfig, RetryConfig, CircuitBreakerConfig
from .errors import (
    JebatError,
    AuthenticationError,
    RateLimitError,
    ValidationError,
    NotFoundError,
    ServerError,
    is_jebat_error,
)
from .models import (
    # Core models
    ChatMessage,
    ChatCompleteRequest,
    ChatCompleteResponse,
    ChatStreamChunk,
    ThinkingMode,
    # Memory
    MemoryLayer,
    MemoryQueryRequest,
    MemoryQueryResponse,
    MemoryAddRequest,
    MemoryAddResponse,
    # Agents
    AgentCreateRequest,
    AgentCreateResponse,
    AgentRunRequest,
    AgentRunResponse,
    AgentStatus,
    # Tools
    ToolCallRequest,
    ToolCallResponse,
    ToolDefinition,
    # Sentinel
    ScanRequest,
    ScanResponse,
    ScanStatus,
    CVEResult,
    ScanReport,
    # DevSuite
    GenerateRequest,
    GenerateResponse,
    ReviewRequest,
    ReviewResponse,
    SandboxRunRequest,
    SandboxRunResponse,
    # Companion
    CompanionChatRequest,
    CompanionChatResponse,
    BriefingRequest,
    BriefingResponse,
    MeetingSummarizeRequest,
    MeetingSummarizeResponse,
    TaskListRequest,
    TaskListResponse,
    # Nexus
    BotCreateRequest,
    BotCreateResponse,
    BroadcastRequest,
    BroadcastResponse,
    ChannelListResponse,
    # MCP
    MCPToolCallRequest,
    MCPToolCallResponse,
    MCPToolListResponse,
    MCPResourceListResponse,
    # Admin
    HealthResponse,
    APIKeyCreateRequest,
    APIKeyCreateResponse,
    APIKeyListResponse,
    # RBAC
    OrgCreateRequest,
    OrgCreateResponse,
    TeamCreateRequest,
    TeamCreateResponse,
    ProjectCreateRequest,
    ProjectCreateResponse,
    RoleAssignRequest,
    AuditLogEntry,
    # Service Accounts
    ServiceAccountCreateRequest,
    ServiceAccountCreateResponse,
    ServiceAccountKeyCreateRequest,
    ServiceAccountKeyCreateResponse,
)

__all__ = [
    # Clients
    "JebatClient",
    "AsyncJebatClient",
    "create_client",
    "create_async_client",
    # Config
    "ClientConfig",
    "RetryConfig",
    "CircuitBreakerConfig",
    # Errors
    "JebatError",
    "AuthenticationError",
    "RateLimitError",
    "ValidationError",
    "NotFoundError",
    "ServerError",
    "is_jebat_error",
    # Models
    "ChatMessage",
    "ChatCompleteRequest",
    "ChatCompleteResponse",
    "ChatStreamChunk",
    "ThinkingMode",
    "MemoryLayer",
    "MemoryQueryRequest",
    "MemoryQueryResponse",
    "MemoryAddRequest",
    "MemoryAddResponse",
    "AgentCreateRequest",
    "AgentCreateResponse",
    "AgentRunRequest",
    "AgentRunResponse",
    "AgentStatus",
    "ToolCallRequest",
    "ToolCallResponse",
    "ToolDefinition",
    "ScanRequest",
    "ScanResponse",
    "ScanStatus",
    "CVEResult",
    "ScanReport",
    "GenerateRequest",
    "GenerateResponse",
    "ReviewRequest",
    "ReviewResponse",
    "SandboxRunRequest",
    "SandboxRunResponse",
    "CompanionChatRequest",
    "CompanionChatResponse",
    "BriefingRequest",
    "BriefingResponse",
    "MeetingSummarizeRequest",
    "MeetingSummarizeResponse",
    "TaskListRequest",
    "TaskListResponse",
    "BotCreateRequest",
    "BotCreateResponse",
    "BroadcastRequest",
    "BroadcastResponse",
    "ChannelListResponse",
    "MCPToolCallRequest",
    "MCPToolCallResponse",
    "MCPToolListResponse",
    "MCPResourceListResponse",
    "HealthResponse",
    "APIKeyCreateRequest",
    "APIKeyCreateResponse",
    "APIKeyListResponse",
    "OrgCreateRequest",
    "OrgCreateResponse",
    "TeamCreateRequest",
    "TeamCreateResponse",
    "ProjectCreateRequest",
    "ProjectCreateResponse",
    "RoleAssignRequest",
    "AuditLogEntry",
    "ServiceAccountCreateRequest",
    "ServiceAccountCreateResponse",
    "ServiceAccountKeyCreateRequest",
    "ServiceAccountKeyCreateResponse",
]

__version__ = "1.0.0"