"""JEBAT Skill Generator — Auto-generate SKILL.md from task descriptions.

Given a task description, generates a complete SKILL.md with:
- YAML frontmatter (name, version, category, trigger)
- Numbered steps with specific commands
- Pitfalls section
- Verification steps

Uses LLM to generate high-quality skill content, then validates
and saves it in JEBAT skill format.

Usage:
    from jebat.features.skill_generator.skill_generator import SkillGenerator
    gen = SkillGenerator()
    skill = await gen.generate("deploy Django app to AWS EC2")
    skill.save("~/jebat/skills/")
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import yaml  # type: ignore
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from jebat.config import load_config
from jebat.llm.chat_runtime import generate_with_failover  # type: ignore

logger = logging.getLogger(__name__)


# ── Data Structures ────────────────────────────────────────────────────────

@dataclass
class GeneratedSkill:
    """A skill generated by the LLM, ready to be saved as SKILL.md."""
    name: str
    description: str
    category: str = "general"
    version: str = "0.1.0"
    author: str = "jebat-generator"
    trigger: str = ""
    steps: List[str] = field(default_factory=list)
    pitfalls: List[str] = field(default_factory=list)
    verification: List[str] = field(default_factory=list)
    references: List[Dict[str, str]] = field(default_factory=list)
    generated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    model_used: str = ""
    raw_llm_output: str = ""
    validated: bool = False

    def to_skill_md(self) -> str:
        """Convert to SKILL.md format."""
        frontmatter = {
            "name": self.name,
            "version": self.version,
            "category": self.category,
            "description": self.description,
            "trigger": self.trigger,
            "author": self.author,
            "generated_at": self.generated_at,
            "model_used": self.model_used,
        }
        fm_str = yaml.dump(frontmatter, default_flow_style=False, sort_keys=False)

        body_parts = []
        if self.steps:
            body_parts.append("## Steps\n")
            for i, step in enumerate(self.steps, 1):
                body_parts.append(f"{i}. {step}\n")
        if self.pitfalls:
            body_parts.append("\n## Pitfalls\n")
            for pit in self.pitfalls:
                body_parts.append(f"- {pit}\n")
        if self.verification:
            body_parts.append("\n## Verification\n")
            for v in self.verification:
                body_parts.append(f"- {v}\n")
        if self.references:
            body_parts.append("\n## References\n")
            for ref in self.references:
                url = ref.get("url", "")
                title = ref.get("title", url)
                body_parts.append(f"- [{title}]({url})\n")

        body = "".join(body_parts)
        return f"---\n{fm_str}---\n\n{body}\n"

    def save(self, directory: str) -> Path:
        """Save as SKILL.md to the specified directory."""
        dir_path = Path(directory)
        skill_dir = dir_path / self.name
        skill_dir.mkdir(parents=True, exist_ok=True)
        skill_file = skill_dir / "SKILL.md"
        skill_file.write_text(self.to_skill_md(), encoding="utf-8")
        logger.info(f"Skill generated and saved: {skill_file}")
        return skill_file


# ── Skill Generator Prompt ──────────────────────────────────────────────────

SKILL_GENERATION_PROMPT = """You are JEBAT's skill generator. Given a task description,
generate a complete SKILL.md file that teaches someone how to perform that task.

SKILL.md format:
```
---
name: <hyphenated-name>
version: 0.1.0
category: <category>
description: <one-line description>
trigger: <when to use this skill>
---

## Steps
1. <specific, actionable step with exact commands where possible>
2. ...

## Pitfalls
- <common mistake or gotcha>
- ...

## Verification
- <how to confirm the task was completed successfully>
- ...
```

Rules:
- Steps must be SPECIFIC with actual commands, not vague advice
- Include exact terminal commands, API endpoints, config keys
- Pitfalls must describe real failure modes, not theoretical risks
- Verification must be checkable (e.g., "run `curl localhost:3000` returns 200")
- Name must be lowercase hyphenated (e.g., "deploy-django-aws")
- Category must be one of: devops, data-science, security, web, api, ml, general
- Trigger must describe WHEN to use this skill (e.g., "When deploying a Django app to AWS EC2")

Task: {task}

Generate the complete SKILL.md content now. Output ONLY the skill content,
no explanation or commentary outside the skill format."""


# ── Skill Generator Core ──────────────────────────────────────────────────────

class SkillGenerator:
    """Auto-generate SKILL.md files from task descriptions using LLM.

    The generator:
    1. Takes a task description
    2. Sends it to the configured LLM with a structured prompt
    3. Parses the LLM output into frontmatter + body sections
    4. Validates the generated skill (checks required sections)
    5. Returns a GeneratedSkill ready to save
    """

    def __init__(self, provider_override: str = None, model_override: str = None):
        self.provider_override = provider_override
        self.model_override = model_override
        self.config = load_config()

    async def generate(self, task: str, name_hint: str = "",
                        category_hint: str = "") -> GeneratedSkill:
        """Generate a skill from a task description.

        Args:
            task: Task description (e.g., "deploy Django to AWS EC2")
            name_hint: Optional name override
            category_hint: Optional category override

        Returns:
            GeneratedSkill with parsed content from LLM
        """
        prompt = SKILL_GENERATION_PROMPT.format(task=task)

        # Call LLM
        try:
            llm_response = await generate_with_failover(
                prompt=prompt,
                provider_override=self.provider_override,
                model_override=self.model_override,
            )
        except Exception as e:
            logger.error(f"LLM generation failed: {e}")
            # Fallback — generate a basic skill without LLM
            return self._generate_fallback(task, name_hint, category_hint)

        # Parse LLM output
        skill = self._parse_llm_output(llm_response, task, name_hint, category_hint)
        skill.raw_llm_output = llm_response
        skill.model_used = self.model_override or self.config.get("default_model", "unknown")

        # Validate
        skill.validated = self._validate_skill(skill)

        return skill

    def _parse_llm_output(self, output: str, task: str,
                           name_hint: str, category_hint: str) -> GeneratedSkill:
        """Parse LLM output into a GeneratedSkill."""
        # Try to extract YAML frontmatter
        fm_match = re.match(r'^---\s*\n(.*?)\n---\s*\n', output, re.DOTALL)
        frontmatter = {}
        body = output

        if fm_match:
            try:
                frontmatter = yaml.safe_load(fm_match.group(1))
                body = output[fm_match.end():]
            except yaml.YAMLError:
                logger.warning("Failed to parse YAML frontmatter, extracting manually")

        # Extract name
        name = name_hint or frontmatter.get("name", "")
        if not name:
            name = re.sub(r'[^\w\s]', '', task).strip().replace(" ", "-").lower()
            name = re.sub(r'-+', '-', name)[:40]

        # Extract description
        description = frontmatter.get("description", task)

        # Extract category
        category = category_hint or frontmatter.get("category", "general")

        # Extract trigger
        trigger = frontmatter.get("trigger", f"When performing: {task}")

        # Parse body sections
        steps = self._extract_section(body, "Steps")
        pitfalls = self._extract_section(body, "Pitfalls")
        verification = self._extract_section(body, "Verification")
        references = self._extract_section(body, "References")

        # Convert references to dict format
        ref_dicts = []
        for ref in references:
            # Try to parse [title](url) format
            link_match = re.match(r'\[([^\]]+)\]\(([^)]+)\)', ref)
            if link_match:
                ref_dicts.append({"title": link_match.group(1), "url": link_match.group(2)})
            else:
                ref_dicts.append({"title": ref, "url": ""})

        return GeneratedSkill(
            name=name,
            description=description,
            category=category,
            trigger=trigger,
            steps=steps,
            pitfalls=pitfalls,
            verification=verification,
            references=ref_dicts,
        )

    def _extract_section(self, body: str, section_name: str) -> List[str]:
        """Extract a numbered/bulleted list section from markdown body."""
        # Find the section heading
        pattern = rf'## {section_name}\s*\n(.*?)(?=\n## |\Z)'
        match = re.search(pattern, body, re.DOTALL)
        if not match:
            return []

        content = match.group(1).strip()
        items = []

        # Numbered list items
        for line in re.findall(r'^\d+\.\s+(.+)$', content, re.MULTILINE):
            items.append(line.strip())

        # Bulleted list items
        for line in re.findall(r'^-\s+(.+)$', content, re.MULTILINE):
            items.append(line.strip())

        return items

    def _validate_skill(self, skill: GeneratedSkill) -> bool:
        """Validate a generated skill has required sections."""
        checks = [
            len(skill.name) > 0,
            len(skill.description) > 0,
            len(skill.steps) >= 2,  # At least 2 steps
            len(skill.pitfalls) >= 1,  # At least 1 pitfall
            len(skill.verification) >= 1,  # At least 1 verification
            skill.category in ("devops", "data-science", "security", "web",
                               "api", "ml", "general", "pentest", "research"),
        ]
        return all(checks)

    def _generate_fallback(self, task: str, name_hint: str,
                            category_hint: str) -> GeneratedSkill:
        """Generate a basic skill when LLM is unavailable."""
        name = name_hint or re.sub(r'[^\w\s]', '', task).strip().replace(" ", "-").lower()[:40]

        return GeneratedSkill(
            name=name,
            description=f"Skill for: {task}",
            category=category_hint or "general",
            trigger=f"When performing: {task}",
            steps=[
                f"Research best practices for: {task}",
                "Identify required tools and dependencies",
                "Follow the standard workflow for this task type",
                "Test the implementation",
            ],
            pitfalls=[
                "Check version compatibility of tools",
                "Verify environment prerequisites",
            ],
            verification=[
                f"Confirm: {task} completed successfully",
                "Run basic smoke test",
            ],
            validated=False,
            model_used="fallback",
        )


# ── CLI Integration ──────────────────────────────────────────────────────────

async def generate_skill(task: str, name: str = "", category: str = "",
                          output_dir: str = "", provider: str = None,
                          model: str = None) -> GeneratedSkill:
    """Convenience function for CLI: generate a skill from task description."""
    generator = SkillGenerator(provider_override=provider, model_override=model)
    skill = await generator.generate(task, name_hint=name, category_hint=category)

    if output_dir:
        skill_path = skill.save(output_dir)
        print(f"Skill saved: {skill_path}")

    return skill